/*
 * Copyright 2016 University of Manchester
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package uk.ac.man.cs.mapreduce.cfg.instructions;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import uk.ac.man.cs.mapreduce.cfg.data.ReadOnlyByteBuffer;

public class Instructions {
    
    public static Instruction getInstruction(ReadOnlyByteBuffer buffer, int bci) {
        int opcode = buffer.peekU1(bci);
        Class<? extends Instruction> klass = instructions[opcode];
        
        try {
            Constructor<? extends Instruction> constructor = klass.getConstructor(ReadOnlyByteBuffer.class, int.class);
            return constructor.newInstance(buffer, bci);
        } catch (IllegalAccessException | IllegalArgumentException 
                | InvocationTargetException | InstantiationException 
                | NoSuchMethodException | SecurityException ex) {            
        }
        return null;
    }
            
    private static final Class<? extends Instruction>[] instructions = new Class[] {
        /* 0x0X */
        StackInstruction.class,
        ConstantInstruction.class,
        ConstantInstruction.class,
        ConstantInstruction.class,
        ConstantInstruction.class,
        ConstantInstruction.class,
        ConstantInstruction.class,
        ConstantInstruction.class,
        ConstantInstruction.class,
        ConstantInstruction.class,
        ConstantInstruction.class,
        ConstantInstruction.class,
        ConstantInstruction.class,
        ConstantInstruction.class,
        ConstantInstruction.class,
        ConstantInstruction.class,
        /* 0x1X */
        null,
        null,
        null,
        null,
        null,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        /* 0x2X */
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        null,
        null,
        /* 0x3X */
        null,
        null,
        null,
        null,
        null,
        null,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        /* 0x4X */
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        AccessInstruction.class,
        null,
        /* 0x5X */
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        /* 0x6X */
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        /* 0x7X */
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        /* 0x8X */
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        AccessInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        /* 0x9X */
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        StackInstruction.class,
        BranchInstruction.class,
        BranchInstruction.class,
        BranchInstruction.class,
        BranchInstruction.class,
        BranchInstruction.class,
        BranchInstruction.class,
        BranchInstruction.class,
        /* 0xAX */
        BranchInstruction.class,
        BranchInstruction.class,
        BranchInstruction.class,
        BranchInstruction.class,
        BranchInstruction.class,
        BranchInstruction.class,
        BranchInstruction.class,
        BranchInstruction.class,
        null,
        null,
        null,
        null,
        ReturnInstruction.class,
        ReturnInstruction.class,
        ReturnInstruction.class,
        ReturnInstruction.class,
        /* 0xBX */
        ReturnInstruction.class,
        ReturnInstruction.class,
        FieldAccessInstruction.class,
        FieldAccessInstruction.class,
        FieldAccessInstruction.class,
        FieldAccessInstruction.class,
        InvokeInstruction.class,
        InvokeInstruction.class,
        InvokeInstruction.class,
        InvokeInstruction.class,
        InvokeInstruction.class,
        NewObjectInstruction.class,
        null,
        null,
        null,
        null,
        /* 0xCX */
        CheckCastInstruction.class,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        /* 0xDX */
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        /* 0xEX */
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        /* 0xFX */
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
    };
}
